export enum RelationshipType {
  SON = 'SON',
  DAUGHTER = 'DAUGHTER',
  MOTHER = 'MOTHER',
  FATHER = 'FATHER',
  SIBLING = 'SIBLING',
  SPOUSE = 'SPOUSE',
  TUTOR = 'TUTOR',
  CAREGIVER = 'CAREGIVER',
  LEGAL_GUARDIAN = 'LEGAL_GUARDIAN',
  OTHER = 'OTHER',
}
